import os
import psycopg2
from backend.src.utils.logging import get_logger

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

logger = get_logger(__name__)

def get_postgres_connection():
    db_dsn = os.getenv("POSTGRES_DSN")
    if not db_dsn:
        logger.error("POSTGRES_DSN environment variable not set.")
        raise ValueError("Postgres DSN not set")
    try:
        conn = psycopg2.connect(db_dsn)
        logger.info("Successfully connected to PostgreSQL.")
        return conn
    except Exception as e:
        logger.error(f"Error connecting to PostgreSQL: {e}")
        raise

def get_content_from_db(content_id: str):
    conn = None
    try:
        conn = get_postgres_connection()
        cur = conn.cursor()
        cur.execute("SELECT text, metadata FROM book_content WHERE id = %s", (content_id,))
        result = cur.fetchone()
        cur.close()
        if result:
            return {"text": result[0], "metadata": result[1]}
        return None
    except Exception as e:
        logger.error(f"Error retrieving content from PostgreSQL: {e}")
        raise
    finally:
        if conn:
            conn.close()