module.exports = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Week 1: Kinematics',
      collapsible: true,
      collapsed: true,
      items: ['kinematics'],
    },
    {
      type: 'category',
      label: 'Week 2: Dynamics',
      collapsible: true,
      collapsed: true,
      items: ['dynamics'],
    },
    {
      type: 'category',
      label: 'Week 3: Control Systems',
      collapsible: true,
      collapsed: true,
      items: ['control-systems'],
    },
    {
      type: 'category',
      label: 'Week 4: Sensors & Actuators',
      collapsible: true,
      collapsed: true,
      items: ['sensors-actuators'],
    },
    {
      type: 'category',
      label: 'Week 5: Perception',
      collapsible: true,
      collapsed: true,
      items: ['perception'],
    },
    {
      type: 'category',
      label: 'Week 6: Localization & Mapping',
      collapsible: true,
      collapsed: true,
      items: ['localization-mapping'],
    },
    {
      type: 'category',
      label: 'Week 7: Path Planning',
      collapsible: true,
      collapsed: true,
      items: ['path-planning'],
    },
    {
      type: 'category',
      label: 'Week 8: Manipulation',
      collapsible: true,
      collapsed: true,
      items: ['manipulation'],
    },
    {
      type: 'category',
      label: 'Week 9: Human-Robot Interaction',
      collapsible: true,
      collapsed: true,
      items: ['human-robot-interaction'],
    },
    {
      type: 'category',
      label: 'Week 10: ROS 2 & Gazebo',
      collapsible: true,
      collapsed: true,
      items: ['ros2-gazebo'],
    },
    {
      type: 'category',
      label: 'Week 11: NVIDIA Isaac Sim',
      collapsible: true,
      collapsed: true,
      items: ['nvidia-isaac'],
    },
    {
      type: 'category',
      label: 'Week 12: Vision-Language-Action Models',
      collapsible: true,
      collapsed: true,
      items: ['vla-models'],
    },
    {
      type: 'category',
      label: 'Week 13: Capstone Project',
      collapsible: true,
      collapsed: true,
      items: ['capstone'],
    },
    {
      type: 'category',
      label: 'Resources',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'html', value: '<em>Papers (Coming Soon)</em>', defaultStyle: true },
        { type: 'html', value: '<em>Datasets (Coming Soon)</em>', defaultStyle: true },
        { type: 'html', value: '<em>Tools (Coming Soon)</em>', defaultStyle: true },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'link', label: 'Discord', href: 'https://discord.gg/panaverse' },
        { type: 'link', label: 'Twitter', href: 'https://twitter.com/Panaverse_Edu' },
      ],
    },
    {
      type: 'category',
      label: 'Gallery',
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'html', value: '<em>Student Projects (Coming Soon)</em>', defaultStyle: true },
      ],
    },
  ],
};
