import React from 'react';

// Code generated by Claude Code.
// Co-Authored-By: Claude <noreply@anthropic.com>

const ContentBlock = ({ title, type, content, imageUrl, code, hardwareRequirements }) => {
  return (
    <div className="margin-bottom--lg">
      {title && <h2>{title}</h2>}
      {type && <p><strong>Type:</strong> {type}</p>}
      {content && <div className="markdown" dangerouslySetInnerHTML={{ __html: content }} />}
      {imageUrl && <img src={imageUrl} alt="Content Screenshot" style={{ maxWidth: '100%' }} />}
      {code && (
        <div className="code-block">
          <h3>Code</h3>
          <pre><code>{code}</code></pre>
        </div>
      )}
      {hardwareRequirements && (
        <div className="hardware-requirements">
          <h3>Hardware Requirements</h3>
          <ul>
            {hardwareRequirements.map((req, index) => (
              <li key={index}>{req}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

export default ContentBlock;
