import React, { useState, useEffect } from 'react';
import styles from './RAGChatbot.module.css';

// Code generated by Claude Code.
// Co-Authored-By: Claude <noreply@anthropic.com>

const RAGChatbot = () => {
  const [selectedText, setSelectedText] = useState('');
  const [query, setQuery] = useState('');
  const [answer, setAnswer] = useState('');
  const [sourceContext, setSourceContext] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [isMinimized, setIsMinimized] = useState(true); // Start minimized as closed
  const [isChatOpen, setIsChatOpen] = useState(false); // Track if chat is open

  const handleTextSelection = () => {
    const text = window.getSelection().toString().trim();
    if (text.length > 10) {
      setSelectedText(text);
      setIsMinimized(false); // Open the chatbot when text is selected
      setIsChatOpen(true); // Set as open when text is selected
    }
  };

  useEffect(() => {
    document.addEventListener('mouseup', handleTextSelection);
    return () => {
      document.removeEventListener('mouseup', handleTextSelection);
    };
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!selectedText) {
      setError('Please select some text from the book first.');
      return;
    }

    setLoading(true);
    setError('');
    setAnswer('');
    setSourceContext([]);

    try {
      const response = await fetch('http://localhost:8000/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query: query, context: selectedText }),
      });

      if (!response.ok) {
        // Check if response is JSON or HTML error page
        const contentType = response.headers.get('content-type');
        if (contentType && contentType.includes('application/json')) {
          const errorData = await response.json();
          throw new Error(errorData.detail || 'Failed to fetch answer from RAG service');
        } else {
          // If it's not JSON, it might be an HTML error page
          const errorText = await response.text();
          throw new Error(`Backend error: ${response.status} - ${errorText.substring(0, 200)}...`);
        }
      }

      const data = await response.json();
      setAnswer(data.answer);
      setSourceContext(data.source_context || []);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setIsMinimized(true); // Minimize to closed state
    setIsChatOpen(false); // Set as closed
    // Don't clear selected text so it persists if user wants to ask more questions
    setQuery('');
    setAnswer('');
    setSourceContext([]);
    setError('');
  };

  const handleOpenChat = () => {
    setIsMinimized(false);
    setIsChatOpen(true);
  };

  return (
    <>
      {isMinimized && !isChatOpen && (
        <button
          onClick={handleOpenChat}
          className={styles.chatbotClosedButton}
          aria-label="Open chat"
        >
          CHAT
        </button>
      )}

      {!isMinimized && isChatOpen && (
        <div className={styles.chatbotContainer}>
          <div className={styles.chatbotHeader}>
            <h3>RAG Chatbot</h3>
            <button onClick={handleClose} className={styles.closeButton}>X</button>
          </div>
          <div className={styles.chatbotContent}>
            <p><strong>Selected Text:</strong> {selectedText.substring(0, 100)}...</p>
            <form onSubmit={handleSubmit}>
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Ask a follow-up question (optional)"
                className={styles.queryInput}
              />
              <button type="submit" disabled={loading} className={styles.submitButton}>
                {loading ? 'Thinking...' : 'Get Answer'}
              </button>
            </form>
            {error && <p className={styles.errorMessage}>Error: {error}</p>}
            {answer && (
              <div className={styles.answerSection}>
                <h4>Answer:</h4>
                <p>{answer}</p>
                {sourceContext.length > 0 && (
                  <div className={styles.sourceContext}>
                    <h5>Source Context:</h5>
                    <ul>
                      {sourceContext.map((source, index) => (
                        <li key={index}>{typeof source === 'string' ? source : source.title || source.source_path || JSON.stringify(source)}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
};

export default RAGChatbot;