import React, { useState, useEffect } from 'react';
import styles from './RAGChatbot.module.css';

// Code generated by Claude Code.
// Co-Authored-By: Claude <noreply@anthropic.com>

const RAGChatbot = () => {
  const [selectedText, setSelectedText] = useState('');
  const [query, setQuery] = useState('');
  const [answer, setAnswer] = useState('');
  const [sourceContext, setSourceContext] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [isVisible, setIsVisible] = useState(false);

  const handleTextSelection = () => {
    const text = window.getSelection().toString().trim();
    if (text.length > 10) {
      setSelectedText(text);
      setIsVisible(true);
    } else {
      setIsVisible(false);
      setSelectedText('');
    }
  };

  useEffect(() => {
    document.addEventListener('mouseup', handleTextSelection);
    return () => {
      document.removeEventListener('mouseup', handleTextSelection);
    };
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!selectedText) {
      setError('Please select some text from the book first.');
      return;
    }

    setLoading(true);
    setError('');
    setAnswer('');
    setSourceContext([]);

    try {
      const response = await fetch('http://localhost:8000/query', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ selected_text: selectedText, query }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || 'Failed to fetch answer from RAG service');
      }

      const data = await response.json();
      setAnswer(data.answer);
      setSourceContext(data.source_context || []);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setIsVisible(false);
    setSelectedText('');
    setQuery('');
    setAnswer('');
    setSourceContext([]);
    setError('');
  };

  if (!isVisible) return null;

  return (
    <div className={styles.chatbotContainer}>
      <div className={styles.chatbotHeader}>
        <h3>RAG Chatbot</h3>
        <button onClick={handleClose} className={styles.closeButton}>X</button>
      </div>
      <div className={styles.chatbotContent}>
        <p><strong>Selected Text:</strong> {selectedText.substring(0, 100)}...</p>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Ask a follow-up question (optional)"
            className={styles.queryInput}
          />
          <button type="submit" disabled={loading} className={styles.submitButton}>
            {loading ? 'Thinking...' : 'Get Answer'}
          </button>
        </form>
        {error && <p className={styles.errorMessage}>Error: {error}</p>}
        {answer && (
          <div className={styles.answerSection}>
            <h4>Answer:</h4>
            <p>{answer}</p>
            {sourceContext.length > 0 && (
              <div className={styles.sourceContext}>
                <h5>Source Context:</h5>
                <ul>
                  {sourceContext.map((source, index) => (
                    <li key={index}>{source}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default RAGChatbot;
