import React, { useState, useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import styles from "./RAGChatbot.module.css";

// Code generated by Claude Code.
// Co-Authored-By: Claude <noreply@anthropic.com>

const RAGChatbot = () => {
    const [selectedText, setSelectedText] = useState("");
    const [query, setQuery] = useState("");
    const [answer, setAnswer] = useState("");
    const [sourceContext, setSourceContext] = useState([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");
    const [showHighlightButton, setShowHighlightButton] = useState(false);
    const [highlightButtonPosition, setHighlightButtonPosition] = useState({
        x: 0,
        y: 0,
    });
    const [chatWindowVisible, setChatWindowVisible] = useState(false); // Controls main chatbot visibility
    const highlightButtonRef = useRef(null);

    const handleTextSelection = () => {
        const selection = window.getSelection();
        const text = selection.toString().trim();

        if (text.length > 10) {
            setSelectedText(text);
            setShowHighlightButton(true);

            const range = selection.getRangeAt(0);
            const rect = range.getBoundingClientRect();
            setHighlightButtonPosition({
                x: rect.right + window.scrollX + 5, // 5px to the right of the selection
                y: rect.top + window.scrollY - 20, // 20px above the selection
            });
        } else {
            setShowHighlightButton(false);
            setSelectedText("");
        }
    };

    const handleAskAiClick = () => {
        setQuery(selectedText); // Pre-fill query with selected text
        setChatWindowVisible(true);
        setShowHighlightButton(false); // Hide the highlight button once chatbot opens
    };

    const toggleChatbotVisibility = () => {
        setChatWindowVisible((prev) => !prev);
        // When hiding the chatbot, clear states
        if (chatWindowVisible) {
            setSelectedText("");
            setQuery("");
            setAnswer("");
            setSourceContext([]);
            setError("");
        }
    };

    useEffect(() => {
        document.addEventListener("mouseup", handleTextSelection);
        return () => {
            document.removeEventListener("mouseup", handleTextSelection);
        };
    }, []);

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!selectedText) {
            setError("Please select some text from the book first.");
            return;
        }

        setLoading(true);
        setError("");
        setAnswer("");
        setSourceContext([]);

        try {
            const apiUrl = `${window.location.protocol}//${window.location.hostname}:8000/rag/query`;
            console.log("Fetching from:", apiUrl); // Log the URL being fetched
            const response = await fetch(apiUrl, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ selected_text: selectedText, query }),
            });

            if (!response.ok) {
                const errorText = await response.text(); // Get raw error text
                console.error("Fetch error response:", errorText);
                throw new Error(
                    errorText || "Failed to fetch answer from RAG service",
                );
            }

            const data = await response.json();
            setAnswer(data.answer);
            setSourceContext(data.source_context || []);
        } catch (err) {
            console.error("RAG Chatbot caught error:", err); // Log the caught error object
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    const handleClose = () => {
        setChatWindowVisible(false);
        setSelectedText("");
        setQuery("");
        setAnswer("");
        setSourceContext([]);
        setError("");
    };

    return (
        <>
            {showHighlightButton && selectedText && (
                <button
                    ref={highlightButtonRef}
                    className={styles.askAiButton}
                    style={{
                        left: highlightButtonPosition.x,
                        top: highlightButtonPosition.y,
                    }}
                    onClick={handleAskAiClick}
                >
                    Ask AI about "{selectedText.substring(0, 20)}..."
                </button>
            )}

            <button
                className={styles.mainChatbotToggle}
                onClick={toggleChatbotVisibility}
            >
                {chatWindowVisible ? "−" : "Chat"}
            </button>

            {chatWindowVisible && (
                <div className={styles.chatbotContainer}>
                    <div className={styles.chatbotHeader}>
                        <h3>RAG Chatbot</h3>
                        <button
                            onClick={toggleChatbotVisibility}
                            className={styles.closeButton}
                        >
                            X
                        </button>
                    </div>
                    <div className={styles.chatbotContent}>
                        {selectedText && (
                            <p>
                                <strong>Selected Text:</strong>{" "}
                                {selectedText.substring(0, 100)}...
                            </p>
                        )}
                        <form onSubmit={handleSubmit}>
                            <input
                                type="text"
                                value={query}
                                onChange={(e) => setQuery(e.target.value)}
                                placeholder="Ask a question..."
                                className={styles.queryInput}
                            />
                            <button
                                type="submit"
                                disabled={loading}
                                className={styles.submitButton}
                            >
                                {loading ? "Thinking..." : "Ask"}
                            </button>
                        </form>
                        {error && (
                            <p className={styles.errorMessage}>
                                Error: {error}
                            </p>
                        )}
                        {answer && (
                            <div className={styles.answerSection}>
                                <h4>Answer:</h4>
                                <p>{answer}</p>
                                {sourceContext.length > 0 && (
                                    <div className={styles.sourceContext}>
                                        <h5>Source Context:</h5>
                                        <ul>
                                            {sourceContext.map(
                                                (source, index) => (
                                                    <li key={index}>
                                                        {source.file_path}{" "}
                                                        (chunk{" "}
                                                        {source.chunk_index})
                                                    </li>
                                                ),
                                            )}
                                        </ul>
                                    </div>
                                )}
                            </div>
                        )}
                    </div>
                </div>
            )}
        </>
    );
};

export default RAGChatbot;
