import sys
import os
from dotenv import load_dotenv
load_dotenv()  # Load environment variables from .env file

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from src.api.routes import router as rag_router
from src.api.chat_routes import router as chat_router
from src.api.embed_routes import router as embed_router
from src.utils.logging import get_logger

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

logger = get_logger(__name__)

app = FastAPI(
    title="Physical AI & Humanoid Robotics RAG API",
    description="API for the interactive RAG chatbot embedded within the book.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:3001", "http://localhost:3002", "http://0.0.0.0:3000"],  # Allow your Docusaurus frontend origin
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(rag_router, prefix="/rag")
app.include_router(chat_router, prefix="/api")
app.include_router(embed_router, prefix="/embed")

@app.get("/health")
async def health_check():
    return {"status": "ok"}