from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from backend.src.api.routes import router as rag_router
from backend.src.utils.logging import get_logger

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

logger = get_logger(__name__)

app = FastAPI(
    title="Physical AI & Humanoid Robotics RAG API",
    description="API for the interactive RAG chatbot embedded within the book.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],  # Allow your Docusaurus frontend origin
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(rag_router, prefix="/rag")

@app.get("/health")
async def health_check():
    return {"status": "ok"}