from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from .api.routes import router as rag_router
from .utils.logging import get_logger
from .data.embed_chapters import embed_chapters

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

logger = get_logger(__name__)

app = FastAPI(
    title="Physical AI & Humanoid Robotics RAG API",
    description="API for the interactive RAG chatbot embedded within the book.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],  # Allow your Docusaurus frontend origin
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

embed_chapters() # Embed chapters on startup
app.include_router(rag_router, prefix="/rag")

@app.get("/health")
async def health_check():
    return {"status": "ok"}