from fastapi import APIRouter
from pydantic import BaseModel
from src.services.rag_service import RAGService
from src.utils.logging import get_logger

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

logger = get_logger(__name__)
router = APIRouter()

class ChatRequest(BaseModel):
    query: str
    context: str = ""

class ChatResponse(BaseModel):
    answer: str
    source_context: list = []

@router.post("/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest):
    """
    Chat endpoint that uses the RAG service with provided context.
    This endpoint is designed to work with the frontend RAG chatbot component.
    """
    try:
        rag_service = RAGService()  # Create instance on-demand to allow proper initialization

        # Use the context as selected_text and query as the follow-up question
        result = rag_service.query_rag(request.context, request.query)
        return ChatResponse(answer=result["answer"], source_context=result["source_context"])
    except Exception as e:
        logger.error(f"Error processing chat request: {e}")
        return ChatResponse(
            answer="I'm sorry, but I couldn't process your request at this time.",
            source_context=[]
        )