from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional
from src.services.embedding_pipeline import EmbeddingPipeline
from src.utils.logging import get_logger

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

logger = get_logger(__name__)
router = APIRouter()

class EmbedRequest(BaseModel):
    docs_dir: Optional[str] = "/home/taimoor/Hackathon_Panaversity/Hackathon/frontend/docs"

class EmbedResponse(BaseModel):
    message: str
    vectors_stored: int
    collection_name: str

@router.post("/embed", response_model=EmbedResponse)
async def embed_documents(request: EmbedRequest):
    """
    Run the embedding pipeline to load Docusaurus docs, chunk them,
    generate embeddings, and store in Qdrant collection.
    """
    try:
        logger.info(f"Starting embedding pipeline for directory: {request.docs_dir}")

        pipeline = EmbeddingPipeline()
        vector_count = pipeline.run_pipeline(docs_dir=request.docs_dir)

        response = EmbedResponse(
            message=f"Successfully embedded documents. {vector_count} vectors stored in collection 'book_content'.",
            vectors_stored=vector_count,
            collection_name="book_content"
        )

        logger.info(f"Embedding pipeline completed. Stored {vector_count} vectors.")
        return response

    except Exception as e:
        logger.error(f"Error in embedding pipeline: {e}")
        raise HTTPException(status_code=500, detail=f"Embedding pipeline failed: {str(e)}")

@router.get("/status")
async def embedding_status():
    """
    Get the status of the embedding collection.
    """
    try:
        from src.data.qdrant_client import get_qdrant_client, COLLECTION_NAME

        client = get_qdrant_client()

        # Try to get collection info
        try:
            collection_info = client.get_collection(COLLECTION_NAME)
            vector_count = collection_info.points_count
            status = "ready"
            message = f"Collection '{COLLECTION_NAME}' exists with {vector_count} vectors"
        except:
            vector_count = 0
            status = "missing"
            message = f"Collection '{COLLECTION_NAME}' does not exist"

        return {
            "status": status,
            "collection_name": COLLECTION_NAME,
            "vector_count": vector_count,
            "message": message
        }
    except Exception as e:
        logger.error(f"Error getting embedding status: {e}")
        return {
            "status": "error",
            "collection_name": COLLECTION_NAME,
            "vector_count": 0,
            "message": f"Error checking status: {str(e)}"
        }