from pydantic import BaseModel
from typing import Optional, List

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

class QueryRequest(BaseModel):
    selected_text: str
    query: str

class QueryResponse(BaseModel):
    answer: str
    source_context: Optional[List[str]] = None