from pydantic import BaseModel
from typing import Optional, List

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

class RAGQueryRequest(BaseModel):
    selected_text: str
    query: Optional[str] = None

class RAGQueryResponse(BaseModel):
    answer: str
    source_context: Optional[List[str]] = None