from fastapi import APIRouter, HTTPException
from .models import QueryRequest, QueryResponse
from ..services.rag_service import RAGService
from ..utils.logging import get_logger

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

logger = get_logger(__name__)
router = APIRouter()
rag_service = RAGService()

@router.post("/query", response_model=QueryResponse)
async def query_rag_endpoint(request: QueryRequest):
    if not request.selected_text or len(request.selected_text) < 10:
        raise HTTPException(status_code=400, detail="Selected text is too short or missing.")

    try:
        result = rag_service.query_rag(request.selected_text, request.query)
        return QueryResponse(answer=result["answer"], source_context=result["source_context"])
    except ValueError as e:
        logger.error(f"RAG service configuration error: {e}")
        raise HTTPException(status_code=500, detail="RAG service configuration error.")
    except Exception as e:
        logger.error(f"Error processing RAG query: {e}")
        raise HTTPException(status_code=500, detail="RAG service temporarily unavailable.")
