import os
import re
from typing import List, Dict

# Code generated by Claude Code.
# Co-Authored-By: Claude <noreply@anthropic.com>

def parse_docusaurus_mdx(file_path: str) -> List[Dict]:
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Extract front matter
    front_matter_match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    front_matter = {}
    if front_matter_match:
        fm_content = front_matter_match.group(1)
        for line in fm_content.splitlines():
            if ':' in line:
                key, value = line.split(':', 1)
                front_matter[key.strip()] = value.strip().strip('\'"')
        content = content[front_matter_match.end():].strip()

    # Split content into chunks (e.g., by headings, paragraphs)
    # For simplicity, we'll treat each paragraph as a chunk for now.
    # A more sophisticated parser might use AST or more complex regex.
    chunks = []
    # Remove import statements for components
    content = re.sub(r'^import .* from .*;\n', '', content, flags=re.MULTILINE)
    paragraphs = re.split(r'\n\n+', content)

    for i, para in enumerate(paragraphs):
        if para.strip(): # Ensure chunk is not empty
            # Attempt to extract a meaningful title for the chunk
            chunk_title = front_matter.get('title', os.path.basename(file_path))
            header_match = re.match(r'^(#+\s*)(.*)', para)
            if header_match:
                chunk_title = header_match.group(2).strip()

            # Basic heuristic to get source context
            source_context = f"{front_matter.get('title', 'Unknown Chapter')} - Section {i+1}"
            if 'sidebar_label' in front_matter:
                source_context = f"{front_matter['sidebar_label']} - Section {i+1}"
            elif 'title' in front_matter:
                source_context = f"{front_matter['title']} - Section {i+1}"

            # Remove MDX components for embedding
            cleaned_para = re.sub(r'<[^>]+?>', '', para) # Remove HTML/MDX tags
            cleaned_para = re.sub(r'{[^}]+?}', '', cleaned_para) # Remove JSX expressions
            cleaned_para = re.sub(r'```.*?```', '', cleaned_para, flags=re.DOTALL) # Remove code blocks

            chunks.append({
                'text': cleaned_para.strip(),
                'metadata': {
                    'file_path': file_path,
                    'title': chunk_title,
                    'source_context': source_context
                }
            })
    return chunks

if __name__ == '__main__':
    # Example Usage:
    # Assuming you have a dummy mdx file for testing
    dummy_mdx_content = """
---
title: Test Chapter
sidebar_label: Test
---

# Introduction

This is the first paragraph of the test chapter. It contains some **important** information.

This is the second paragraph.

<ContentBlock title="Example" content="Some example content" />

```python
print("Hello")
```

## Conclusion

Final thoughts.
"""
    dummy_file_path = "dummy_chapter.mdx"
    with open(dummy_file_path, 'w') as f:
        f.write(dummy_mdx_content)

    parsed_chunks = parse_docusaurus_mdx(dummy_file_path)
    for i, chunk in enumerate(parsed_chunks):
        print(f"--- Chunk {i+1} ---")
        print(f"Text: {chunk['text']}")
        print(f"Metadata: {chunk['metadata']}")
        print("\n")

    os.remove(dummy_file_path)
