import React, { useState, useEffect, useMemo } from 'react';
import clsx from 'clsx';
import {ThemeClassNames} from '@docusaurus/theme-common';
import {useDoc} from '@docusaurus/plugin-content-docs/client';
import Heading from '@theme/Heading';
import MDXContent from '@theme/MDXContent';
import RAGChatbot from '@site/src/components/RAGChatbot';
import PersonalizeButton from '@site/src/components/PersonalizeButton';
import { fetchUserBackground, personalizeContent } from '@site/src/utils/personalizationApi';
import usePersonalization from '@site/src/hooks/usePersonalization';

// Code generated by Claude Code.
// Co-Authored-By: Claude <noreply@anthropic.com>

function useSyntheticTitle() {
  const {metadata, frontMatter, contentTitle} = useDoc();
  const shouldRender =
    !frontMatter.hide_title && typeof contentTitle === 'undefined';
  if (!shouldRender) {
    return null;
  }
  return metadata.title;
}

export default function DocItemContent({children}) {
  const syntheticTitle = useSyntheticTitle();
  const {metadata} = useDoc();
  const content = metadata.content || ''; // Get the raw markdown content
  const [isPersonalized] = usePersonalization();
  const [personalizedChildren, setPersonalizedChildren] = useState(null);
  const [isLoadingPersonalization, setIsLoadingPersonalization] = useState(false);
  const [userBackground, setUserBackground] = useState(null);

  const memoizedFetchUserBackground = useMemo(() => {
    return async (userId) => {
      const background = await fetchUserBackground(userId);
      setUserBackground(background);
    };
  }, []);

  useEffect(() => {
    // Fetch user background (simulated for now)
    memoizedFetchUserBackground('user123');
  }, [memoizedFetchUserBackground]);

  useEffect(() => {
    async function applyPersonalization() {
      if (isPersonalized && userBackground && content) {
        setIsLoadingPersonalization(true);
        const personalizedMarkdown = await personalizeContent(content, userBackground);
        setPersonalizedChildren(personalizedMarkdown);
        setIsLoadingPersonalization(false);
      } else {
        setPersonalizedChildren(null); // Reset when personalization is off
      }
    }
    applyPersonalization();
  }, [isPersonalized, userBackground, content]);

  const displayedChildren = isPersonalized && personalizedChildren && !isLoadingPersonalization
    ? personalizedChildren
    : children;

  return (
    <div className={clsx(ThemeClassNames.docs.docMarkdown, 'markdown')}>
      {syntheticTitle && (
        <header>
          <Heading as="h1">{syntheticTitle}</Heading>
        </header>
      )}
      <PersonalizeButton />
      {isLoadingPersonalization ? (
        <p>Loading personalized content...</p>
      ) : (
        <MDXContent>{displayedChildren}</MDXContent>
      )}
      <RAGChatbot />
    </div>
  );
}
